### ISSUE TITLE
Disabling mod with custom sprite map does not correctly invalide chache

### ISSUE THREAD

**Issue by Mr-Auto** [spelunky-fyi/Playlunky#11]
So i made a mod that changes hud.png using json file, it just replaces some hud items with one transparent pixel from my png file. Playing the mod works fine, but then when i play with the mod turn off (modlunky2), the items are still invisible, the mod is not active as it does more stuff that are not present. Clearing the cache solves the problem.

the mode if needed: https://spelunky.fyi/mods/m/item-sprites-randomizer/

**Comment by Malacath-92** [comment]
Right, I remember that more work needs to be done in order to correctly invalidate the cache for custom mappings. Thanks for reminding me  🙏

**Comment by Malacath-92** [comment]
Fixed in v0.8.1
