### ISSUE TITLE
Patched exe

### ISSUE THREAD

**Issue by Ameichi** [spelunky-fyi/Playlunky#15]
2021-07-15 01:19:40,484: You're using Playlunky against a patched exe. For best results use Playlunky on a vanilla exe

i don't have a vanilla exe how do i use Playlunky without it?

**Comment by Malacath-92** [comment]
Do you mean you patched your .exe with mods or is your .exe pirated?

**Comment by gmjosack** [comment]
This is a modlunky warning. Playlunky and exes packed with modlunky historically haven't played well together. You should restore your exe or verify your game files from the Pack tab.

**Comment by Malacath-92** [comment]
I was just confused by the wording of "I don't have a vanilla exe" otherwise my answer would be the same

**Comment by Ameichi** [comment]
Yes the version im using for Modding is a Repack/Torrented version so I can keep it offline and away from my steam version Sent from Mail for Windows 10 From: Malacath-92Sent: Thursday, July 15, 2021 4:36 AMTo: spelunky-fyi/PlaylunkyCc: Ameichi; AuthorSubject: Re: [spelunky-fyi/Playlunky] Patched exe (#15) Do you mean you patched your .exe with mods or is your .exe pirated?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gmjosack** [comment]
We don't support pirated versions of the game.

**Comment by Ameichi** [comment]
By we are you saying your program is made to not work with all non official versions of the game or just that you do not support the idea of torrenting? Do I need to edit your program to allow that or is there a way I can make a second copy of my steam version for use with modding so it will stay offline and away from my steam version with achievements?  Sent from Mail for Windows 10 From: garySent: Saturday, July 17, 2021 8:12 AMTo: spelunky-fyi/PlaylunkyCc: Ameichi; AuthorSubject: Re: [spelunky-fyi/Playlunky] Patched exe (#15) We don't support pirated versions of the game.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
