### ISSUE TITLE
Playlunky tab won't load

### ISSUE THREAD

**Issue by randompug** [spelunky-fyi/Playlunky#26]
No idea what I'm doing, so I could just have done something wrong. All I did was download modlunky 2, put it in the spelunky 2 folder, and run it. The Playlunky tab won't load and this is the error message

2022-08-31 17:18:06,126: Failed to register tab Level Editor: Traceback (most recent call last):
  File "modlunky2\ui__init.py", line 429, in register_tab
  File "modlunky2\ui\levels\tab.py", line 86, in init__
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'

**Comment by Malacath-92** [comment]
This is a Modlunky issue, not a Playlunky issue. But I see you got help on the Discord either way.
> Under the settings tab, you probably don't have an install directory set. Select the directory containing Spel2.exe and restart modlunky2
