### ISSUE TITLE
This version of Spelunky 2 is not supported by playlunky Error upon launch

### ISSUE THREAD

**Issue by gillisllc** [spelunky-fyi/Playlunky#28]
For the last few days when i launch Playlunky using Modlunky 2 I get the following error:

This version of Spelunky 2 is not supported by playlunky, please update you game or check if there is a new version of Playlunky Available.

Spelunky Version: could not be verified
Supported Version 1.25.2

Press OK to start without Playlunky or Cancel to yolo

If you press Cancel it does not load any mods but the game plays and loads from the steam install:

Mods in use:
Co-op shared Camera

I think this has to do with the Spelunky 2 August Patch?

Is there anything that can be done? My wife and her sister have 900+ hours into the game and play it everyday... but will not play without this mod. I am hoping to fix it soon for them to play.

Thanks all.

**Comment by Mr-Auto** [comment]
This update broke a lot of stuff, it will take time to fix everything

For now you can downgrade to the previous version of Spelunky2 https://gist.github.com/Dregu/ff06f4d5ed808fe7772d253ac7edbb30
