### ISSUE TITLE
Modlunky refuses to start 

### ISSUE THREAD

**Issue by CherryStormNova** [spelunky-fyi/Playlunky#30]
The application was unable to start correctly (0xc0000142).

**Comment by Mr-Auto** [comment]
This is repo for playlunky, modlunky is actually separate application (https://github.com/spelunky-fyi/modlunky2).
Also would be nice to have some more info other then generic error message.

But i guess you actually trying to start Playlunky not modlunky? if that's the case, there this obvious issue open already: #28
