### ISSUE TITLE
Possible memory leak with scripts mods on Linux under wine

### ISSUE THREAD

**Issue by Malabarba** [spelunky-fyi/Playlunky#36]
**Game version**: 1.27
**Wine version**: 6.13
**Playlunky**: Nightly version from Oct 9th (playlunky_nightly_33E9D4A.zip)

I'll start by saying I know Linux is not officially supported. But I figured I'd report anyway in case it might be a simple fix.

## Steps for a bugless execution
- Install Spelunky via steam for linux.
- Download Playlunky and extract it in the Spelunky directory (`~/.steam/steam/steamapps/common/Spelunky 2/`)
- Create an empty directory called `my-test-mod` inside `Mods/Packs/`, and add it to `load_order.txt`.
- Launch Playlunky via Wine (I've attached the script I use below, for the exact envvars).
- Once the game reaches the Start Screen (the one with the art of Ana holding a torch), simply wait.

For me, here, the game sits at a healthy 5.7% memory usage.  (monitored via `htop`)

## Steps for the bug
- Inside the directory called `my-test-mod`, place an **empty** file called `main.lua`.
- Launch Playlunky via Wine again and, again, wait on the Start Screen.
- This time there will be a "Playlunky ####-modified" watermark on the bottom left.

For me, here, the game starts at 5.9% memory usage and increases at a rate of approx 1% per minute (that's about 188MB/min) even if I just sit and stare at the start screen (no inputs, no changes).  
After about an hour of gameplay, the game will run out of available memory and the OS starts swapping or crashes.

## Further notes
- I'm on Kubuntu 20.10
- Sprite mods don't cause this problem, it's something specific to script mods.
- At first I thought it was the script's fault, but then I tested with a completely empty script and the problem persisted, so I presume it's something in playlunky.
- I don't experience this issue with scripts loaded via Overlunky (at least, not at this alarming rate).

**Comment by Malabarba** [comment]
FWIW, I downloaded the latest nightly here ([playlunky_nightly_649FF71.zip](https://github.com/spelunky-fyi/Playlunky/releases/download/nightly/playlunky_nightly_649FF71.zip)) just to check if the problem persists, and it seems to be even worse. :sweat_smile: 
Now it grows at about 3% per minute (basically every other second I see a 0.1% increase).

**Comment by Malacath-92** [comment]
Do you know if this is exclusive ro wine or just a regular old bug? I don't have a setup to try this and I don't really have the time to make one either.

**Comment by Malacath-92** [comment]
Seems to be an issue on Windows too, interesting that no one reported this so far. I'll take a closer look later.

**Comment by Malacath-92** [comment]
Oh this is worse than I thought. The text rendering functions leak, likely `prepare_text_for_rendering` allocates. No time to check right now, so I hand it over to someone else for now, but some reverse engineering should get to the bottom of this.

**Comment by Malacath-92** [comment]
Should be fixed once the next Nightly comes live (building right now). Thanks so much for finding this issue @Malabarba <3
