### ISSUE TITLE
Playlunky and Overlunky won't start for me

### ISSUE THREAD

**Issue by SmellyJacket** [spelunky-fyi/Playlunky#41]
When I click play on Playlunky, it doesn't work for any version I try, and Overlunky doesn't link with my regular Spelunky 2 anymore, is there a reason for this?

**Comment by Dregu** [comment]
There could be a hundred reasons, but since you're the only one complaining it's probably something you or your computer did, not us. I'm not going to try and guess what, but you can start at https://github.com/spelunky-fyi/overlunky#troubleshooting

**Comment by Malacath-92** [comment]
No user interaction and not enough details to help anyways, closing
