### ISSUE TITLE
Hundun slows down every restart?

### ISSUE THREAD

**Issue by mauvealerts** [spelunky-fyi/Playlunky#42]
I recently tried checking something and noticed that Hundun seemed slow. In [this video](https://youtu.be/lFsHBa_BEXQ):
* Start adventure mode, attach x64dbg just to edit `theme_start`, then detach
* No mods are loaded
* No pre-existing playlunky.ini nor imgui_playlunky.ini
* Launched via Modlunky2
* Nightly, version 08e0cab-modified. Specifically the `playlunky_nightly_C0C88C3.zip` released at 2023-01-04T15:53:42Z

This doesn't reproduce with:
* Stable
* or with Speedrun Mode enabled
* or resetting in Dwelling

**Comment by mauvealerts** [comment]
Configs and trimmed log (.txt added to make GH happy):
* [playlunky.ini.txt](https://github.com/spelunky-fyi/Playlunky/files/10349610/playlunky.ini.txt)
* [imgui_playlunky.ini.txt](https://github.com/spelunky-fyi/Playlunky/files/10349612/imgui_playlunky.ini.txt)
* [spelunky-trimmed.log.txt](https://github.com/spelunky-fyi/Playlunky/files/10349611/spelunky-trimmed.log.txt)

**Comment by Dregu** [comment]
So the missing_pipes bugfix is broken and is getting enabled by default if no setting exists. Possibly something broken with the new entity virtuals. Didn't check what's wront with the script or virtuals, just fixed it being enabled in the first place in https://github.com/spelunky-fyi/Playlunky/pull/43

**Comment by Dregu** [comment]
Fixed deprecated api pointing to nil in OL.

**Comment by mauvealerts** [comment]
I think this is totally fixed with Dregu's changes: #43 and https://github.com/spelunky-fyi/overlunky/commit/f2af1075060e4882c6632a9b4914db1a61999d19
