### ISSUE TITLE
Playlunky doesn't work for me.

### ISSUE THREAD

**Issue by swaizzen** [spelunky-fyi/Playlunky#46]
When I try to run "playlunky_installer.exe" nothing happens, even when I run it as administrator I've tried with several versions:
nightly
stable
0.16.1
0.11.0
The problem continues even if I run it with Modlunky or without.

(I use DeepL Traductor so..)

**Comment by gmjosack** [comment]
Without more information about what is not working it will be pretty hard to diagnose.

Are you using the latest Steam version? Playlunky only works for the Steam release, not Windows Store.
You might also need to make sure you don't have an anti-virus that is preventing it from being run.

**Comment by swaizzen** [comment]
I have no anti-virus and the windows security is not enabled, i use the latest steam version

**Comment by Mr-Auto** [comment]
With modlunky, when you choose nightly version from the list, is it problem with downloading it or when you hit play?
is there any error listed in modlunky or the playlunky is just not starting at all?

**Comment by swaizzen** [comment]
with modlunky when i select nightly it does : 2023-06-06 10:07:53,249: Executing Playlunky Launcher with nightly\playlunky_launcher.exe but nothing happen

**Comment by swaizzen** [comment]
> With modlunky, when you choose nightly version from the list, is it problem with downloading it or when you hit play? is there any error listed in modlunky or the playlunky is just not starting at all?

when i hit play

**Comment by swaizzen** [comment]
So someone know how can i stop this error?

**Comment by Mr-Auto** [comment]
In modlunky, when you go to the settings page, is the path to the Spelunky 2 correct?

**Comment by lumzyhere** [comment]
> In modlunky, when you go to the settings page, is the path to the Spelunky 2 correct?

I'm having the same issue, the path is connected to Spelunky 2

**Comment by Malacath-92** [comment]
Not enough info to help, refer to Discord for these kinds of issues in the future as live chat is much better to help troubleshoot, closing
