### ISSUE TITLE
Mod Options panel has no scroll bar

### ISSUE THREAD

**Issue by Cosine256** [spelunky-fyi/Playlunky#48]
The Mod Options panel has no visible scroll bar, even if the options extend past the bottom of the panel. This happens with script mods with a lot of options, such as Randomizer. Scrolling with the mouse wheel still works.

I believe this is being caused by the combination flag `ImGuiWindowFlags_NoDecoration` on the ImGui window:
https://github.com/spelunky-fyi/Playlunky/blob/08628db9c53a6125afb920f88542953a1951c815/source/playlunky/mod/mod_manager.cpp#L1026-L1029
That flag is redundant with the others, since `NoTitleBar`, `NoResize`, and `NoCollapse` are already explicitly set on the window, so all it serves to do is add `NoScrollbar`.

**Comment by Dregu** [comment]
Enabled scrollbars and other window controls in #51
