### ISSUE TITLE
Stickers not generating in 0.6.2, worked in 0.5.10

### ISSUE THREAD

**Issue by Dregu** [spelunky-fyi/Playlunky#8]
I'm just getting default stickers in 0.6.x with a bunch of generic character mods that showed generated stickers properly in 0.5.10.

**Comment by Malacath-92** [comment]
Yeah, there's a bug that I introduced when merging the old sticker gen and the new entity sheet functionality. It doesn't regen when the regular character sheets are changed. Have a fix locally that I will submit with the Lua beta in a few days.

For now you either live with this or you delete your sticker DDS file in Packs/.Db manually

**Comment by gmjosack** [comment]
> Lua beta in a few days

:eyes:

**Comment by Dregu** [comment]
> For now you either live with this or you delete your sticker DDS file in Packs/.Db manually

That's the thing, I didn't have any .db folders.

**Comment by Malacath-92** [comment]
That is very odd... Clean packs and a bunch of old style character mods works on my end. I'll try to figure out if I can find out what's going on for you.

**Comment by Malacath-92** [comment]
Can you try v0.7.0-beta?

**Comment by Malacath-92** [comment]
Closing because we determined on Discord that this works again for all of us
